### ISSUE TITLE
Dynamo DB store implementation

### ISSUE THREAD

**Issue by fd1az** [hallgren/eventsourcing#111]
@fd1az I close this PR. Please send a link to your repo when you feel ready.

_Originally posted by @hallgren in https://github.com/hallgren/eventsourcing/issues/103#issuecomment-1961170078_

Hi! @hallgren 
This is the link to the repo https://github.com/fd1az/dynamo-es

I have used the library https://golang.testcontainers.org/ for testing; there's no need to set up a Docker container... and it works very well for adding it to a CI... I think it would be a good option for other implementations such as eventStoreDB.

**Comment by hallgren** [comment]
Very nice!

I have now added a ref to your event store in the readme. 

I'll give https://golang.testcontainers.org/ a look. Thanks 👍

**Comment by hallgren** [comment]
@fd1az I now use testcontainers to test the esdb event store. Thanks for the insight. :)
