### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by hallgren** [hallgren/eventsourcing#23]

**Comment by jdgiotta** [comment]
@hallgren any ETA on supplying a license?

**Comment by hallgren** [comment]
Hi, I need to check with the author of the project i forked. But if his OK with it I will make it as open as possible with no restrictions. (Need to read up on what license is the most suited) 

@jdgiotta Just curious, do you have any plans using this package in a project?

/Morgan

**Comment by hallgren** [comment]
added MPLv2 license file
